production:
  backend_api:
    url: ???
    audience: ???

development:
  backend_api:
    domain: dev-precisely.auth0.com
    audience: precisely-backend-api
  frontend_simple:
    domain: dev-precisely.auth0.com
